//------------------------------------------------------------------------------
//  Copyright 2007-2019 by Jyh-Ming Lien and George Mason University
//  See the file "LICENSE" for more information
//------------------------------------------------------------------------------

#pragma once

#include "polygon.h"

namespace masc{
namespace polygon{

///////////////////////////////////////////////////////////////////////////////
// This convex hull implemetation realizes the idea from
// A. Melkman, "On-line construction of the convex hull of a simple polygon",
// Info. Proc. Letters 25, 11-12 (1987)
///////////////////////////////////////////////////////////////////////////////

// prints the current convex hull
void printConvexHull(vector<ply_vertex*> &convexHullPoints);
    
// Converts a point to an array to be used with existing helper functions;
void toArray(const Point2d& point, double (&doubleArr)[2]);
    
// Determine if point2 is the left of the line generated by the segment point0 -> point1.
// Returns false if point2 is to the right OR on the line.
int isLeft(const Point2d& point0, const Point2d& point1, const Point2d& point2);    

// Implementation of isLeft function for ply_vertex points.
int isLeft(ply_vertex* p0, ply_vertex* p1, ply_vertex* p2);
    
//
// compute the convex hull of the given (subset) polygon
//
// e mush be reachable from s
//
void hull2d ( ply_vertex* startVertex, ply_vertex* endVertex, std::__cxx11::list< masc::polygon::ply_vertex* >& hull );

}//end namespace polygon
}//end namespace masc
